### ISSUE TITLE
feat: load from csv file

### ISSUE THREAD

**Issue by wey-gu** [wey-gu/jupyter_nebulagraph#15]
as titled.

**Comment by sdehury34** [comment]
So what I have to do is basically load data from csv file right?
Hi I will be do this task. Please assign this task to me.

**Comment by wey-gu** [comment]
Dear @sdehury34 ,

Yes! If needed, we could break this into multiple tasks!

Generally, we need to:

- define how CSV columns were mapped to NebulaGraph Vertex/Edge and the properties
- read files in a batch way and compose BULK INSERT queries.

We have such a thing in go with https://github.com/vesoft-inc/nebula-importer , but as we are using this in Jupyter, for ease of tests, thus we don't have to impl. things in that full-functional fashion/shape.

**Comment by wey-gu** [comment]
I think I can do this now.
