### ISSUE TITLE
Render edge with Rank awareness

### ISSUE THREAD

**Issue by hhlcode** [wey-gu/jupyter_nebulagraph#23]
![Uploading 微信图片_20240302
![微信图片_20240302222007](https://github.com/wey-gu/ipython-ngql/assets/63626546/1bc3f196-7612-4290-911c-9f1e8320795b)
222000.jpg…]()
一条相同的查询语句，在分别在nebula-studio和ipython-ngql 中查询，出现的结果完全不一样

**Comment by wey-gu** [comment]
Thanks, I need to implement rank on edges :)

**Comment by wey-gu** [comment]
It's now fixed:

<img width="1073" src="https://github.com/wey-gu/jupyter_nebulagraph/assets/1651790/e97c4d4d-fa99-47e2-9972-96684e5c1bbf">
