### ISSUE TITLE
ng_draw can't draw the graph with Chinese characters

### ISSUE THREAD

**Issue by lushunn** [wey-gu/jupyter_nebulagraph#6]
Error  log: UnicodeEncodeError: 'gbk' codec can't encode character '\xa9' in position 230710: illegal multibyte sequence

**Comment by wey-gu** [comment]
> Error  log: UnicodeEncodeError: 'gbk' codec can't encode character '\xa9' in position 230710: illegal multibyte sequence

Aha, that I didn't test! Let me see and fix, thanks!
