### ISSUE TITLE
Silent ngql execution for ng_draw

### ISSUE THREAD

**Issue by BeautyyuYanli** [wey-gu/jupyter_nebulagraph#61]
The result of ngql sometime can be dummy, when I just want to draw the graph. Maybe a way to silently run ngql can help.

**Comment by wey-gu** [comment]
> The result of ngql sometime can be dummy, when I just want to draw the graph. Maybe a way to silently run ngql can help.

Yeah maybe with

%ng_draw match xxx 

?

**Comment by wey-gu** [comment]
see here, pr coming

<img width="1320" alt="ng_draw_query" src="https://github.com/wey-gu/jupyter_nebulagraph/assets/1651790/a6e3b2d4-0320-4287-bd2f-537cff77c1de">
